;
; File generated by cc65 v 2.18 - Git 2f3955d
;
	.fopt		compiler,"cc65 v 2.18 - Git 2f3955d"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_decomp_flat
	.importzp	passout

_out = passout

; ---------------------------------------------------------------
; u8 decomp_flat(u8 *out);
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_decomp_flat: near

;
; memset(out, *in, 64);
;
	lda	_mbyte

	ldy	#$3F
@loop:	sta	(_out),y
	dey
	bpl	@loop
;
; return 0;
;
	ldx     #$00
	txa

	rts

.endproc

