;
; File generated by cc65 v 2.18 - Git 2f3955d
;
	.fopt		compiler,"cc65 v 2.18 - Git 2f3955d"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_decomp_uncompressed
	.importzp	passin, passout

_in = passin
_out = passout

; ---------------------------------------------------------------
; u8 decomp_uncompressed(const u8 *in, u8 *out);
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_decomp_uncompressed: near

;
; memcpy(out, in, 32);
;
	ldy	#31
@loop:
	lda	(_in),y
	sta	(_out),y
	dey
	bpl	@loop
;
; return 32;
;
	ldx     #$00
	lda     #$20

	rts

.endproc

